name: NISAR_EA_Workshop_2024_10
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10
  - pip
  # For running
  - asf_search
  - boto3
  - earthaccess
  - geopandas
  - h5py
  - hyp3lib>=3,<4
  - imageio
  - ipykernel
  - ipympl
  - matplotlib-base
  - numpy
  - rasterio
  - rioxarray
  - scipy
  - pyproj
  - s3fs
  # For packaging, and testing
  - ruff
  - setuptools
  - setuptools_scm
  - wheel
  - pytest
  - pytest-console-scripts
  - pytest-cov
